### ISSUE TITLE
Problem ze skanowaniem kodów po wpisaniu kodu ręcznie

### ISSUE THREAD

**Issue by rodkiewicz** [KlubJagiellonski/pola-android#112]
Jak odtworzyć: Odpalamy apke, wpisujemy na klawiaturze kod (może być błędny) po czym próbujemy zeskanować kod.

Błąd znika, jeśli wyłączymy na chwile aplikacje lub odpalimy menu i wrócimy do widoku skanowania. 
Wersja apki: 1.8 (30)
System: Android 11 (samsung s10)

**Comment by rafalgawlik** [comment]
@rodkiewicz zrobisz fix?

**Comment by rodkiewicz** [comment]
tak

**Comment by rafalgawlik** [comment]
fix powinien być prosty, a błąd wygląda na ważny

**Comment by rodkiewicz** [comment]
Problem nie wynika z logiki aplikacji, tylko błędu w bibliotece. 
https://github.com/journeyapps/zxing-android-embedded/issues/581
Problem do zamknięcia chyba? @rafalgawlik

**Comment by rafalgawlik** [comment]
zamykamy
