### ISSUE TITLE
Możliwość klikania w elementy w widoku klawiatury 

### ISSUE THREAD

**Issue by rodkiewicz** [KlubJagiellonski/pola-android#113]
Jak odtworzyć: Jeśli odpalimy klawiaturę wbudowaną w aplikacje i poklikamy w obszary gdzie znajdują inne elementy interfejsu z poprzedniego widoku (np logo poli, latarka, przycisk menu lub lista zeskanowanych produktów) to zobaczymy że widok klawiatury "przepuszcza" kliknięcia.  
Wersja apki: 1.8 (30)
System: Android 11 (samsung s10)

**Comment by karkaminski** [comment]
robie to!

**Comment by karkaminski** [comment]
@rodkiewicz 
wygląda na to, że się udało #129

**Comment by rodkiewicz** [comment]
no i bardzo fajnie, teraz tylko @rafalgawlik zrobi PR i będzie ticket do zamknięcia.

**Comment by rafalgawlik** [comment]
Ok na pr

**Comment by rafalgawlik** [comment]
zmergowane
