### ISSUE TITLE
Zmiana napisu na przycisku zbiórki 

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#134]
Prośba o zmianę napisu na przycisku ze „WSPIERAJ APLIKACJĘ POLA” na „Potrzebujemy 1 zł”. 

Łącznie z [issues #68](https://github.com/KlubJagiellonski/pola-android/issues/68)
![image](https://user-images.githubusercontent.com/52166969/117130629-9fa9a580-ada0-11eb-803c-df86229bdb30.png)

**Comment by rafalgawlik** [comment]
zmergowane
