### ISSUE TITLE
Przyjaciele Poli dla marek Lidla

### ISSUE THREAD

**Issue by karkaminski** [KlubJagiellonski/pola-android#145]
Źle wyświetla się przycisk "przyjaciele poli" dla marek Lidla.
Już naprawiam! :) 
![obraz](https://user-images.githubusercontent.com/44138626/119186533-811dfc80-ba78-11eb-9a24-9cae762d7a19.png)

**Comment by rafalgawlik** [comment]
naprawione i wydane 1.9.1
