### ISSUE TITLE
Configure integration with Travis-CI

### ISSUE THREAD

**Issue by dziobas** [KlubJagiellonski/pola-android#17]
The configuration is already merged: #12 
The github account admin should configure the integration as described in: 
https://travis-ci.org/getting_started

**Comment by dziobas** [comment]
ping @gkapusta @tajchert @jakublipinski @paweljaneczek

**Comment by gkapusta** [comment]
Only @jakublipinski has the power to do it.

**Comment by dziobas** [comment]
ok 😄

**Comment by jakublipinski** [comment]
Done @dziobas
