### ISSUE TITLE
Przycisk wyszukiwarka tekstowa w menu

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#222]
Zgodnie z ustaleniem, warto informować użytkownika o tym, że mamy wyszukiwarkę tekstową. Dlatego warto dodać do Menu przycisk "Wyszukiwarka tekstowa" z linkiem do nowej strony. Proponuję dodać to jako drugie od góry, pod "O aplikacji Pola".

Podam link jak tylko będzie gotowy.

![image](https://user-images.githubusercontent.com/52166969/140910609-47ddd35d-b9ba-4b98-8d8e-486f277df469.png)

**Comment by WezSieTato** [comment]
Trzeba też podpiąć analitykę zgodnie z https://docs.google.com/spreadsheets/d/1fqoX2H2P9wUwLRQiRoKljkEVEIG6Jkre-j_mvtrbI3M/edit#gid=0 :)

**Comment by rafalgawlik** [comment]
merged
