### ISSUE TITLE
Ręczne wpisywanie kodów

### ISSUE THREAD

**Issue by przemo509** [KlubJagiellonski/pola-android#23]
Cześć, 

Chciałbym zasygnalizować potrzebę ręcznego wpisywania kodów kreskowych (cyfra po cyfrze). Przydatne to będzie zwłaszcza w telefonach ze słabym aparatem fotograficznym (np. mój Samsung Galaxy Young bez autofocusa) jak również przy słabych warunkach oświetleniowych. Możliwe, że dzięki temu można by zejść z wymaganą wersją API Androida, ale tu mogę się mylić, może coś innego wymaga tej wersji API.

Pozdrawiam
Przemysław Sadło

**Comment by gkapusta** [comment]
Dodanie opcji ręcznego wpisywania kodów kreskowych jest w planach i pracę są już w toku. Prosimy o cierpliwość.

**Comment by jakublipinski** [comment]
Dostępne od wersji 1.5
