### ISSUE TITLE
Usunąć Fabric.io. Zintegrować Firebase Analytics.

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-android#28]
Usunąć Fabric.io.

Dodać Firebase do Androida:
https://console.firebase.google.com/u/0/project/pola-8682d/settings/general/
(Pliku z kluczem prywatnym nie dodajemy do GitHub'a!)

Integrujemy Crash Reporting:
https://firebase.google.com/docs/crash/android

Lista wydarzeń do dodania (https://firebase.google.com/docs/analytics/android/events) jest pod adresem:
https://docs.google.com/spreadsheets/d/1fqoX2H2P9wUwLRQiRoKljkEVEIG6Jkre-j_mvtrbI3M/edit#gid=0

**Comment by jakublipinski** [comment]
Mój wynik testów raportowania do Firebase:
cc: @gkapusta @gewaraz 
`code` w `company_received` powinien zawierać kod kreskowy, a zawiera chyba HTTP Response Code
`ai_requested` w `company_received` powinno mieć wartość `true` lub `false` (jest 0 lub 1)
`code` w `report_stared` powinien zawierać kod kreskowy, a zawiera chyba id produktu
`code` w `report_finished` powinien zawierać kod kreskowy, a zawiera chyba id produktu
event powinien nazywać się `aipics_started` a nie `aipicks_started`
nie przychodzą `menu_item_opened`

**Comment by gkapusta** [comment]
Zgłoszone błędy poprawione w https://github.com/KlubJagiellonski/pola-android/commit/bcb32a8af37fbba0e704a4d15f5858ab8a3771ab

**Comment by jakublipinski** [comment]
Potwierdzam, poprawione

**Comment by jakublipinski** [comment]
Zamknięte w `1.6`
