### ISSUE TITLE
Zepsute zdjęcia z "Naucz Polę"

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-android#34]
Niektóre zdjęcia z "Naucz Polę" są "zepsute", np.

![](https://pola-ai-pics.s3.amazonaws.com/5901550002955/312_0_b38e37dc-838d-11e7-a2f4-e6792f0fcee9.png)

**Comment by gkapusta** [comment]
Potencjalny fix w https://github.com/KlubJagiellonski/pola-android/commit/039d854fec6e8f1ec000ec16daf4fd38bfc9b150 
Do przetestowania w 1.6

**Comment by jakublipinski** [comment]
Czekamy czy nadal będa przychodzić zespute zdjęcia...
