### ISSUE TITLE
Menu w aplikacji wg. projektu

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-android#37]
![pola_informacje-33](https://user-images.githubusercontent.com/1204581/29483498-a35b0c44-845c-11e7-8c79-1cea42695172.png)

**Comment by gewaraz** [comment]
W apce androidowej menu ma byc kolejnym widokiem?

**Comment by jakublipinski** [comment]
Screenshot jest z iOS'a. Na Androidzie powinno być coś pewnie bardziej androidowego... Masz jakąś propozycję?

**Comment by gewaraz** [comment]
Zauważyłem :D 
Pewnie. Moge wziąć tego taska.

**Comment by rafalgawlik** [comment]
Task można zamknąć
