### ISSUE TITLE
Android 8.0 Oreo Nexus 5x odwrócony ekrain

### ISSUE THREAD

**Issue by rafalgawlik** [KlubJagiellonski/pola-android#40]
Telefon znajduje się w normalnej pozycji - widok jest odwrócony do góry nogami
https://ibb.co/bNijrk

**Comment by jakublipinski** [comment]
Z tego co wiem to używamy tam standardowego API, więc to wygląda na błąd systemowy. Mam rację @gkapusta, @KKonradMC ?

**Comment by gewaraz** [comment]
Zgadza się. 
Problem znalazłem w kiedy jeszcze Andorid 8.0 było Betą, teraz jest już produkcyjną wersją i błąd dalej się pojawia. 

Drastyczną opcją jest tymczasowe wyłączenie uczenia Poli dla Android 8.0

**Comment by jakublipinski** [comment]
Czy to nie jest związane z tym: https://stackoverflow.com/questions/22376749/camera-preview-is-upside-down - sprawdziłbyś byś?

**Comment by rafalgawlik** [comment]
cannot reproduce
