### ISSUE TITLE
Pola w sklepie F-Droid

### ISSUE THREAD

**Issue by tomikmar** [KlubJagiellonski/pola-android#41]
Czy poza Google Play możecie dodać aplikację Pola również do sklepu F-Droid (https://f-droid.org/)?

W razie czego mogę z tym pomóc.

**Comment by mik-laj** [comment]
Powiązane: https://github.com/KlubJagiellonski/pola-android/issues/7#issue-116452472 być może nie aktualne.

**Comment by jakublipinski** [comment]
@tomikmar tak jak w powyższym komentarzu. Pola używa Google App Services więc jak rozumiem nie może być częścią F-Droid :(
(Tu jest np. dyskusja dlaczego nie ma Signal w F-Droid: https://forum.f-droid.org/t/signal-discussion-about-google-play-alternative/95)

**Comment by Etua** [comment]
@jakublipinski Zainstalowałem Polę na urządzeniu bez GAPPS i jedyną niedziałającą funkcją jest odtwarzanie filmu o tym, jak należy kręcić produktem w celu nauczenia programu o jego wyglądzie. Najwyraźniej komponenty Google nie są wymagane.

**Comment by tomikmar** [comment]
@jakublipinski Ja również od dłuższego czasu używam Polę na LineageOS 7.1 bez bibliotek Google. 

Może przynajmniej dało by się zrobić tą zależność opcjonalną (jeśli naprawdę jest niezbędna do niektórych funkcji)? Myślę że wiele aplikacji rozwiązało ten problem w taki sposób.

**Comment by Etua** [comment]
@tomikmar Jest trochę programów na Androida, których twórcy generują wersję do Google Play i do F-Droid z innym komponentem lub bez pewnej funkcji. Na przykład komunikator Conversations różni się brakiem push z Google Cloud Messaging, informacje o powiadomieniach są przesyłane inną metodą.

**Comment by jakublipinski** [comment]
Panowie, to jest projekt open-source. Jeśli możecie usunąć zależność GAPPS to poprosimy o Pull Request. Jeśli uważacie, że Pola powinna być w F-Droid, to ją tam wrzućcie. Chyba zespół Poli nie jest do tego potrzebny?

**Comment by Etua** [comment]
@jakublipinski W zasadzie wyrażenie aprobaty ze strony twórców programu jest jednym z wymogów dodania go do repozytorium F-Droid.
