### ISSUE TITLE
Test rozpoznawania produktów po zdjęciu

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-android#47]
Przystępujemy do testów rozpoznawania produktów po zdjęciu - aby sprawdzić jak to będzie działać.

1. Odpal projekt zlokalizowany pod adresem https://github.com/KlubJagiellonski/pola-ai/tree/master/android_camera. Jest to przykładowy kod z `Tensorflow` pracujący na modelu, który został już wyćwiczony na naszych zdjęciach. Model jest na razie bardzo prymitywny. Dla niektórych produktów mieliśmy tylko 20 zdjęć. Z czasem będzie lepszy. "Potrafi" rozpoznać następujące produkty:
```
Muszynianka Naturalna woda mineralna wysokozmineralizowana magnezowo-wapniowa 1,5 l
Cisowianka Naturalna woda mineralna niegazowana niskosodowa 1,5 l
Muszyna Skarb Życia Naturalna woda mineralna wysokozmineralizowana lekko gazowana 1,5 l
NIVEA Creme Krem 250 ml
Żywiec Zdrój Woda niegazowana 1,5 l
Nałęczowianka 1,5 l niegaz P/L - butelka
Inka Rozpuszczalna kawa zbożowa 200 g
Tyskie Gronie Piwo jasne 500 ml
Kamis Musztarda sarepska 185 g
Sierpc Ser królewski 135 g
Nałęczowianka 0,5 l niegaz P/L - butelka
Staropolanka 2000 Naturalna woda mineralna wysokozmineralizowana lekko gazowana 1,5 l
Mlekovita Masło Polskie ekstra bez dodatków 82% 200 g
Diamant Cukier biały 1 kg
ŁOMŻA NIEPASTER BUT 0,5L BZ 45/20/50 szt.
Piwniczanka Woda mineralna lekko gazowana 1,5 l
Żywioł od Żywiec Zdrój SA Woda źródlana gazowana 1,5 l
Mlekovita Polskie Mleko spożywcze 3,2% 1 l
Perła Export Piwo jasne 500 ml
Cisowianka Naturalna woda mineralna niegazowana niskosodowa 0,5 l
ŁOMŻA EXPORT BUT 0,5L BZ DHP 20/20/50 szt.
Woda Żywiec Zdrój niegazowana  1.75 l i
Nałęczów Zdrój Naturalna woda mineralna niegazowana 1,5 l
Cisowianka Naturalna woda mineralna gazowana niskosodowa 1,5 l
Muszyna Skarb Życia Naturalna woda mineralna wysokozmineralizowana gazowana 1,5 l
```
Uwaga. Ten projekt ma w sobie 4 różne aplikacje. Nas interesuje tylko `TF Classify`

2. Założ nowy `branch` np. `pola-ai` i przełącz się na niego (w między czasie chcemy jeszcze odpalić Polę 1.6.1 (https://github.com/KlubJagiellonski/pola-android/milestone/3))

3.  Przenieś przykładowy kod z punktu 1, tak aby odpalał się w głownym ekranie Poli. Wyświetlaj rozpoznane nazwy produktów na ekranie.

4. Rozpoznane nazwy produktów kończą się liczbą, która jest `id` producenta. Musimy znaleźć warunki na podstawie których stwierdzimy, że aplikacja poprawnie rozpoznała producenta po wyglądzie. Trzeba to będzie wyznaczyć eksperymentalnie. Na początek proponuję zrobić wersję, która będzie na ekranie wyświetlać 10 ostatnio rozpoznanych `id` producentów, pod warunkiem, że skuteczność rozpoznania była przynajmniej `95%`. Na tej podstawie wyznaczymy lepsze warunki.

**Comment by gewaraz** [comment]
biorę jak coś! :)

**Comment by gewaraz** [comment]
"Perła Export Piwo jasne 500 ml" to już wiem na czym testować :dagger: :smile:
