### ISSUE TITLE
Po każdym zrobieniu zdjęcia staje się ono jedynym w zgłoszeniu

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-android#48]
Od użytkownika:
Chciałem zgłosić pewną nieprawidłowość w aplikacji. 
Gdy chcę zgłosić Państwu nowy kod, którego nie ma w bazie danych i chcę dodać zdjęcia, to po każdym zrobieniu zdjęcia staje się ono jedynym w zgłoszeniu. Nie można dodać więcej niż jedno zdjęcie. 
Poza tym aplikacja super. Oby tak dalej.

**Comment by rafalgawlik** [comment]
Wiadomo jaki to telefon? U mnie to działa tak jak trzeba.

**Comment by jakublipinski** [comment]
`Samsung Galaxy S3`

**Comment by jakublipinski** [comment]
Tu jest jeszcze potwierdzenie w `review`: https://play.google.com/store/apps/details?id=pl.pola_app&reviewId=Z3A6QU9xcFRPRldsYXVjTE96VTQyX2x0LWxZUXdLX3lJcW1vZkhrSHFVaFRmSDR4eXhJVlBIeFY1ckthUDF1WmxaRWxIT0F2MC0tUG1JOWhicVFaYUNtZDMw&hl=pl

**Comment by rafalgawlik** [comment]
Nie mogę zdobyć tego modelu telefonu.
