### ISSUE TITLE
A teraz zeskanuj całą łazienkę

### ISSUE THREAD

**Issue by qduaty** [KlubJagiellonski/pola-android#49]
Ta wiadomość jest „creepy”, bo sugeruje, że Pola wyciąga wnioski z miejsca skanowania a nie samych kodów produktów. Skanowanie produktów zużywalnych po zakupie nie jest nadużyciem.

**Comment by jakublipinski** [comment]
Dzięki za zgłoszenie. Poprawione w https://github.com/KlubJagiellonski/pola-backend/commit/0791a697a7f7858cc76707318ce67dd6587cf85c (ten tekst jest z backend'u)
