### ISSUE TITLE
Zmiana ekranu startowego

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#57]
Wymieniamy ekran startowy. Nowa wersja we wszystkich rozmiarach w załączniku. Połączone z issues #58 

![320x480](https://user-images.githubusercontent.com/52166969/86399596-d823b300-bca7-11ea-95d8-77a2aeb082bd.png)
![480x800](https://user-images.githubusercontent.com/52166969/86399597-d954e000-bca7-11ea-8ddf-40c7a44d5203.png)
![720x1280](https://user-images.githubusercontent.com/52166969/86399598-d954e000-bca7-11ea-91bc-802beab539d3.png)
![960x1600](https://user-images.githubusercontent.com/52166969/86399601-d9ed7680-bca7-11ea-852a-26536e6e177a.png)
![1280x1920](https://user-images.githubusercontent.com/52166969/86399603-da860d00-bca7-11ea-96e6-3ac3761ec52f.png)

**Comment by rafalgawlik** [comment]
merged & delivered
