### ISSUE TITLE
Przycisk Klubu Przyjaciół Poli

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#58]
W lewym górnym rogu zastępujemy logo Poli przyciskiem, którzy przenosi użytkownika do zakładki „Przyjaciele Poli”.

![KPPpol](https://user-images.githubusercontent.com/52166969/85606581-99607e00-b653-11ea-91b9-60dfad560727.jpg)
![KPPol2](https://user-images.githubusercontent.com/52166969/85606600-9e253200-b653-11ea-92aa-377a4ba335d3.jpg)

**Comment by rafalgawlik** [comment]
Wydane w 1.8
