### ISSUE TITLE
Wklejanie kodów kreskowych

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#59]
Jak na screenie. Czy da się wklejać skopiowany wcześniej kod w polu tekstowym.

![image](https://user-images.githubusercontent.com/52166969/85608019-f6106880-b654-11ea-97b1-a321713d91ba.png)
![KPPol3](https://user-images.githubusercontent.com/52166969/85608889-d168c080-b655-11ea-8586-ffd3790feda6.jpg)

**Comment by karkaminski** [comment]
W aplikacji na Androida nie ma problemu. Można wkleić kod po dłuższym przytrzymaniu pola tekstowego.
![obraz](https://user-images.githubusercontent.com/44138626/119189712-b0366d00-ba7c-11eb-8c9e-a066ab25b0b1.png)

**Comment by MatPerowicz** [comment]
Ok, dzięki 🙂

pt., 21 maj 2021, 21:38 użytkownik karkaminski ***@***.***>
napisał:
