### ISSUE TITLE
Sczytywanie kodów kreskowych z galerii zdjęć [Konsultacje]

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#60]
Użytkownicy proszą o możliwość dodania funkcji pozwalającej na załadowanie zdjęcia z galerii i sczytania kodu z tego zdjęcia. Proszę o informację czy to możliwe i ile ewentualnie  czasu zajmie,

![Screenshot_20200706_231256](https://user-images.githubusercontent.com/52166969/86645263-8ac48000-bfde-11ea-9f96-e63b7df35145.jpg)

**Comment by jakublipinski** [comment]
Można wpisać kod ręcznie. Można zeskanować zdjęcie innym telefonem. Sugeruję robić takie zmiany, które są przydatne większej liczbie osób a nie pojedynczym.

**Comment by MatPerowicz** [comment]
Tak samo mu odpisałem. Dzięki za opinię.

Pozdrawiam,
Mateusz

wt., 7 lip 2020, 09:49 użytkownik Jakub Lipinski <notifications@github.com>
napisał:
