### ISSUE TITLE
Błędny kraj pochodzenia produktu na produktach marki własnej

### ISSUE THREAD

**Issue by MaciejMasper** [KlubJagiellonski/pola-android#63]
Witam serdecznie,

do produktów marek własnych sieci sklepów Lidl przypisywany jest błędny kraj pochodzenia. Bazuje on na kodach EAN, które świadczą o kraju, w którym zarejestrowany jest właściciel sieci handlowej, sprzedającej dane produkty a nie j realny kraj pochodzenia produktu sprzedawanego w ww sieci.
Przykład:
czekolada z kodem EAN 4056489185888 wyprodukowana przez polskiego przedsiębiorcę w PL

Probblem nie jest jednostkowy - dotyczy on większości produktów PrivateLabel sieci Lidl. 

Podawane przez aplikację informacje są niezgodne z rzeczywistością i wprowadzają konsumentów w błąd. 
W celu identyfikacji produktów i ich prawdziwych krajów pochodzenia, proszę o przesłanie  danych do kontaktu z osobą mogącą te dane skorygować.

Z góry dziekuję,

**Comment by MatPerowicz** [comment]
Dzień dobry,

dziękujemy za wiadomość. Wyświetlane użytkownikom informacje z założenia dotyczą firm/producentów, a nie konkretnych produktów.

Dane kontaktowe znajdują się pod tym linkiem:
https://klubjagiellonski.pl/profil/mateuszperowicz/

Pozdrawiam
