### ISSUE TITLE
Ciemny motyw

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#64]
Propozycja wyglądu aplikacji, gdy mamy ustawiony tryb ciemny w telefonie:

ekran startowy: tło z białego zmienia się na czarne, logo klubu malujemy na biało, a w logu Poli część czarną (kontur) na biało
ekran skanowania produktu i wpisywania kodu zostają bez zmian,
ekran firmy, informacje + zakładki, zgłaszanie błędy: to co białe -> czarne i na odwrót, czerwone elementy bez zmian, plus trza pokombinować z szarym (wydaje mi się, że odwrócenie koloru powinno dać dobry efekt)

**Comment by MatPerowicz** [comment]
@rafalgawlik link do ekranu startowego w ciemnej wersji https://drive.google.com/drive/folders/1nDXshGOj79JQ1pMgz9UvT9Sh8xkX_OVl?usp=sharing

**Comment by karkaminski** [comment]
@rafalgawlik jak utknąłem z poprzednim PR to się zabrałem za to, moze Ci się przyda :) https://github.com/karkaminski/pola-android/tree/DarkTheme

**Comment by MatPerowicz** [comment]
Ok, dzięki 🙂

pon., 12 paź 2020, 21:30 użytkownik karkaminski <notifications@github.com>
napisał:

**Comment by karkaminski** [comment]
![image](https://user-images.githubusercontent.com/44138626/137641892-690489d0-8460-44e3-9719-8c116200c820.png)

**Comment by karkaminski** [comment]
![image](https://user-images.githubusercontent.com/44138626/137641910-6f1f0677-989f-4fb4-af48-fcd1794f1858.png)

![image](https://user-images.githubusercontent.com/44138626/137641917-a2256826-dfd7-4259-b6aa-4b337449c1d4.png)

**Comment by karkaminski** [comment]
![image](https://user-images.githubusercontent.com/44138626/137642300-d7ea01cf-5f73-4d9d-819e-668924aa5528.png)

**Comment by rafalgawlik** [comment]
@karkaminski wrzucaj PR

**Comment by rafalgawlik** [comment]
zamykam bo merged
