### ISSUE TITLE
Zależność od Google Play Services

### ISSUE THREAD

**Issue by rczajka** [KlubJagiellonski/pola-android#7]
Kod aplikacji jest na wolnej licencji, ale posiada własnościową zależność w postaci Google Play Services (Mobile Vision API, konkretnie Barcode API). Przez to:
- aplikacja nie może być faktycznie uznana za wolną i np. trafić do repozytorium [F-Droid](https://f-droid.org);
- aplikacja nie działa na urządzeniach, które nie mają własnościowych bibliotek Google (np. na moim).

Jak rozumiem, celem użycia tego API jest odczytanie kodu kreskowego. Rozwiązaniem byłoby skanowanie kodów kreskowych [via intent](https://github.com/zxing/zxing/wiki/Scanning-Via-Intent).

**Comment by tajchert** [comment]
>aplikacja nie działa na urządzeniach, które nie mają własnościowych bibliotek Google (np. na moim).
Zachęcałbym do sprawdzenia :) 

Tak, zgadza się że mamy taką zależność lecz jest to w tej chwili "martwa" (nie używana). Aktualnie aplikacja używa Zxinga do skanowania, stąd nie widze problemu dlaczego miałaby u Ciebie nie działać.

Polecam zajrzeć do klasy https://github.com/KlubJagiellonski/pola-android/blob/master/app/src/main/java/pl/pola_app/ui/fragment/ScannerFragment.java oba przypadki (jeśli urządzenie ma Google Play Services lub są niedostępne) są obsługiwane (choć aktualnie jest to wyłączone ze względu na niedostateczny czas do testów tego rozwiązania).
W przyszłości planujemy odblokowanie tego jeśli będziemy pewni że działa to lepiej i co najmniej równie stabilnie.

Niestety wygląda aplikacji uniemożliwia skanowanie przez użycie Intentu.

**Comment by rczajka** [comment]
Racja. U mnie nie zadziałało przez mój, zupełnie niezależny, błąd.

**Comment by Etua** [comment]
#41  Jak w powiązanym zgłoszeniu:

> Zainstalowałem Polę na urządzeniu bez GAPPS i jedyną niedziałającą funkcją jest odtwarzanie filmu o tym, jak należy kręcić produktem w celu nauczenia programu o jego wyglądzie. Najwyraźniej komponenty Google nie są wymagane.
