### ISSUE TITLE
Oznaczenie Przyjaciół Poli, pojawia się na wszystkich firmach

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#74]
Po zeskanowaniu produktu firmy będącej Przyjacielem Poli, ikona która miała wyróżniać takie firmy pojawia się także na innych wynikach skanowania.

Screen:

![image](https://user-images.githubusercontent.com/52166969/95177005-ed840e00-07bd-11eb-9717-7ffe55fbd03a.png)

**Comment by rafalgawlik** [comment]
Wydane w najbliższej wersji 1.9.
