### ISSUE TITLE
Tekst nachodzi na siebie

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-android#83]
Użytkownicy zgłaszają, że w jednym miejscu tekst nachodzi na siebie i jest nieczytelny.

![image](https://user-images.githubusercontent.com/52166969/107220374-8fd52c00-6a12-11eb-8fd8-ed8231bd0243.png)

**Comment by rafalgawlik** [comment]
Wydane w najbliższej wersji
