### ISSUE TITLE
Pasek "udzał polskiego kapitału"

### ISSUE THREAD

**Issue by karkaminski** [KlubJagiellonski/pola-android#88]
Pasek "udzał polskiego kapitału" nie wskazuje prawidłowo danych. Zawsze jest cały szary, bez wzlędu na to ile jest %.
![obraz](https://user-images.githubusercontent.com/44138626/110319468-3c54fe80-800f-11eb-9dd2-227733599d62.png)

**Comment by rafalgawlik** [comment]
zmergowane, zamykamy
