### ISSUE TITLE
Nie czyta kodów, które się całkowicie nie mieszczą w okienku

### ISSUE THREAD

**Issue by Cysioland** [KlubJagiellonski/pola-android#9]
Jeżeli kod jest dość długi, i wychodzi poza obszar okienka, to aplikacja go nie czyta.

**Comment by tajchert** [comment]
Bo też taki jest zamiar że to okienko ma określać obszar gdzie aplikacja skanuje kod - tak aby uniknąć niechcianych skanów produktów w tle.

**Comment by Cysioland** [comment]
Tylko np. napoje z Biedronki mają kod przez całą długość etykiety.

Możecie ewentualnie dać możliwość ręcznego wpisania kodu

**Comment by tajchert** [comment]
Można prosić o podesłanie zdjęcia takiego kodu kreskowego?

**Comment by Cysioland** [comment]
![Jasne, że można](https://cloud.githubusercontent.com/assets/913522/12990387/700d7810-d10a-11e5-862b-0d58abc2d6a5.JPG)

**Comment by tajchert** [comment]
Ahhh, to ma sens... otwieram z powrotem bo myślałem o poziomie. Rzeczywiście jest to błąd aplikacji i do poprawienia.

**Comment by jakublipinski** [comment]
Proszę o sprawdzenie czy problem wciąż istnieje w wersji 1.5 (zaktualizowaliśmy bibliotekę skanującą kody)

**Comment by Cysioland** [comment]
Taa, już działa
